#!/bin/bash
# Deploy script for Schlüsselkasten V2
# Pulls latest code from GitHub, stamps version.py with the git tag + build
# number, updates dependencies, and restarts the service.
#
# Usage: ./deploy.sh [--no-restart]
#   --no-restart   skip stopping/starting the systemd service

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_DIR="$(dirname "$REPO_DIR")/SKV2-env"
SERVICE_NAME="schluesselkasten.service"
NO_RESTART=false

for arg in "$@"; do
    case "$arg" in
        --no-restart) NO_RESTART=true ;;
        *) echo "Unknown argument: $arg"; exit 1 ;;
    esac
done

cd "$REPO_DIR"

# ---------------------------------------------------------------------------
# 1. Stop the service so we don't deploy into a running process
# ---------------------------------------------------------------------------
if [ "$NO_RESTART" = false ] && systemctl is-active --user --quiet "$SERVICE_NAME"; then
    echo "[deploy] Stopping $SERVICE_NAME ..."
    systemctl --user stop "$SERVICE_NAME"
fi

# ---------------------------------------------------------------------------
# 2. Pull from GitHub
# ---------------------------------------------------------------------------
echo "[deploy] Pulling from remote ..."
git fetch --tags
git pull

# ---------------------------------------------------------------------------
# 3. Derive version: <tag>+<commits-since-tag>  (e.g. "2.1.0+5")
#    Falls back to commit hash when no tag is present.
# ---------------------------------------------------------------------------
TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
COMMITS_SINCE=$(git rev-list "${TAG}..HEAD" --count 2>/dev/null || echo "0")

# Strip a leading 'v' from the tag if present
TAG="${TAG#v}"

if [ "$COMMITS_SINCE" -eq 0 ]; then
    VERSION="${TAG}"
else
    VERSION="${TAG}+${COMMITS_SINCE}"
fi

echo "[deploy] Version: $VERSION"

# ---------------------------------------------------------------------------
# 4. Write version to version.py
# ---------------------------------------------------------------------------
cat > "$REPO_DIR/version.py" << EOF
# Single source of truth for the software version string.
# All modules import from here instead of defining __version__ locally.
# Generated by deploy.sh — do not edit manually.

__version__ = "${VERSION}"
EOF

echo "[deploy] version.py updated."

# ---------------------------------------------------------------------------
# 5. Update Python dependencies
# ---------------------------------------------------------------------------
if [ -f "$VENV_DIR/bin/activate" ]; then
    echo "[deploy] Updating dependencies ..."
    source "$VENV_DIR/bin/activate"
    pip install --quiet --upgrade -r "$REPO_DIR/requirements.txt"
else
    echo "[deploy] Warning: venv not found at $VENV_DIR — skipping pip install."
fi

# ---------------------------------------------------------------------------
# 6. Restart service
# ---------------------------------------------------------------------------
if [ "$NO_RESTART" = false ]; then
    echo "[deploy] Starting $SERVICE_NAME ..."
    systemctl --user start "$SERVICE_NAME"
fi

echo "[deploy] Done. Deployed version $VERSION."
